apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: digital-ecosystem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ghcr.io/YOUR_GITHUB_USERNAME/service-auth:latest
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: jwt_secret
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: digital-ecosystem
type: Opaque
stringData:
  jwt_secret: supersecret
