apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: digital-ecosystem
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: data
  namespace: digital-ecosystem
spec:
  selector:
    app: data
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: digital-ecosystem
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8080
