name: CI/CD

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push auth
        uses: docker/build-push-action@v4
        with:
          context: ./service-auth
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/service-auth:latest

      - name: Build and push data
        uses: docker/build-push-action@v4
        with:
          context: ./service-data
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/service-data:latest

      - name: Build and push gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/api-gateway:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
      - name: Decode kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV
      - name: Deploy manifests
        run: kubectl apply -f k8s/
